### ISSUE TITLE
Unexpected behavior when extracting from tensors with higher dimension

### ISSUE THREAD

**Issue by dfalbel** [rstudio/tensorflow#111]
I'm creating a function subset_tensor define with:

```
subset_tensor <- function(x, a, b){
  x[,0:(a-2), 0:(b-2),]
}
```

Then I apply it to a placeholder tensor:

```
k <- tf$placeholder(tf$float32, shape = c(1L, 600L, 600L, 3L))
subset_tensor(k, 600, 600)
#> Error in eval(expr, envir, enclos) : object 'b' not found
```

Note that it works if call directly:

```
k[,0:(600-2), 0:(600-2),]
Tensor("StridedSlice_5:0", shape=(1, 599, 599, 3), dtype=float32)
```

When I define a function `subset_tensor2` for a 2 dimension tensor, It works fine.

```
subset_tensor2 <- function(x, a, b){
  x[0:(a-2), 0:(b-2)]
}
subset_tensor2(l, 600, 600)
#> Tensor("StridedSlice_6:0", shape=(599, 599), dtype=float32)
```

Am I doing something wrong?

**Comment by jjallaire** [comment]
This must have to do with the way evaluation is performed. @goldingn Do you have any insight as to why the function call based version wouldn't work here?

**Comment by goldingn** [comment]
Good catch @dfalbel!

Yes, the evaluation of extract calls is a bit of a nightmare. The generic extract function has arguments: `i, j, ... , drop = TRUE` - i.e. the first two indices named and subsequent ones aren't. In order to interpret missing indices as meaning 'all entries' in the higher dimensions, the calls for those indices are caught and then evaluated later.

Turns out the bug you found is just because those calls are evaluated in the wrong environment, hence 'b' could not be found. I've just submitted [a PR](https://github.com/rstudio/tensorflow/pull/112) to fix this, and added a simple test. Using the version in that PR, your example works fine for me:

```r
devtools::install_github('goldingn/tensorflow@bb32c5d')

subset_tensor <- function(x, a, b){
  x[,0:(a-2), 0:(b-2),]
}

k <- tf$placeholder(tf$float32, shape = c(1L, 600L, 600L, 3L))
subset_tensor(k, 600, 600)
#> Tensor("StridedSlice_5:0", shape=c(1, 599, 599, 3), dtype=float32)
```

As an aside for the interested: I have a cleaner set up in [this project](https://github.com/goldingn/greta#greta-probabilistic-modelling-with-tensorflow) that fully [maps R's Extract and Replace syntax to Tensorflow ops](https://github.com/goldingn/greta/blob/master/R/extract_replace_combine.R). We could consider copying that over to this package, but we previously decided the tensorflow package extract syntax should implement the behaviour that is common to both R and numpy (except for 0-indexing). I think that's still the right decision, since everything else about using the tensorflow package is pythonic.
