### ISSUE TITLE
Rstudio can't use the GPU version of Tensorflow but R in command line can

### ISSUE THREAD

**Issue by madcarrot** [rstudio/tensorflow#121]
Hi,

As the title describes, I successfully installed Tensorflow through the package, upgraded it to the GPU version, runs fine in Python and R called from bash, but doesn't work with Rstudio... Below are the details:

I'm running on Ubuntu 16.04 with CUDA 8.0 and CUdnn 5.1 installed.

I successfully installed the CPU version of Tensorflow through R with the instruction you provided:
```R
library(tensorflow)
install_tensorflow()
```
and it worked. Since R calls Tensorflow through a Python API, I thought I might as well replace it with the GPU version and get much faster compute speed. 

So I did a 
```bash
sudo -H pip install --upgrade  $TF_PYTHON_URL
```
where `$TF_PYTHON_URL` points to the url for the python 3.6 GPU version `.whl` file. The installation went successfully, and I was able to do `python -c 'import tensorflow as tf; sess = tf.InteractiveSession()'` and get the log stating that Tensorflow was successfully initialized with my GPUs.

Then under the `r-tensorflow` Conda environment, I entered `R` through command line, and tried 
```R
library(tensorflow)
sess <- tf$InteractiveSession()
```
and it worked! I saw the exact same message as the python call.

However, when I entered RStudio, the same call would fail as RStudio raises error:
```
Error: Installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 /home/user/anaconda3/envs/r-tensorflow/bin/python3.6

...
```

so it did search inside the `r-tensorflow` Conda environment and didn't find Tensorflow.

I did a little more research and saw that the R Tensorflow package calls [`import`](https://github.com/rstudio/tensorflow/blob/c1f2fa1b2266497d9c69b3e1ee7c32181955d548/R/package.R#L33) from the [`Reticulate`](https://github.com/rstudio/reticulate/blob/10b4c15db6b614aaa410fc5a37ede2885bcc7ef9/R/python.R#L31) package. I tried running 
```
import("tensorflow")
```

and it gave me the following error:
```
Error in py_module_import(module, convert = convert) : 
  ImportError: Traceback (most recent call last):
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot op
```

The `libcublas.so.8.0` file is stored in `/usr/local/cuda-8.0/lib64`, and I have my `LD_LIBRARY_PATH` environment variable pointing to it.

I suspected that it might be due to RStudio not having the correct environment variables set up as in my `~/.bashrc`, but 
```
system("python -c 'import tensorflow as tf; sess = tf.InteractiveSession()'")
```
within RStudio would show the correct initialization message.

I also tried to manually set up all the environment variables (e.g. `LD_LIBRARY_PATH`, `CUDA_HOME`, `PATH`) through `Sys.setenv`, and it still doesn't work.

Would you mind helping me with it? I think this will enable a huge performance potential for Tensorflow on RStudio.

**Comment by jjallaire** [comment]
Thanks *very* much for the detailed report. I agree that it is critical that we get this working correctly. My strong suspicion (echoed in your bug reports) is that this boils down to an LD_LIBRARY_PATH issue, whereby RStudio on Linux isn't seeing the CUDA environment variables in ~/.bashrc. This is a general limitation of desktop applications on Linux (they don't execute .bashrc). Note also that LD_LIBRARY_PATH must be set before the process executes (which is why `Sys.setenv` doesn't work).

The reason why `system` works is that it executes a shell (and therefore does see .bashrc).

There are a couple of workarounds which I think will get you past this but I'm also interested in pursuing a solution that requires no workarounds, so would be grateful for any additional help you can provide in diagnosing/testing. Here are three workarounds:

1) Start within a bash shell then execute `rstudio`. This should launch RStudio with the same environment as you have in bash.

2) Edit the RStudio .desktop file (or create a custom one) so that it sees the CUDA environment variables (https://help.ubuntu.com/community/EnvironmentVariables#Launching_desktop_application_with_an_environment_variable).

3) Add the CUDA environment variables to the "global" desktop environment (https://superuser.com/questions/555081/ubuntu-environment-setting-for-gui-session-or-making-the-same-with-terminal).

I don't really want to ask every user that wants to take advantage of CUDA to do this though. Another approach may be for the tensorflow package to find CUDA and do an explicit `dyn.load("lib", local = FALSE)` on the CUDA libraries before attempting to `import("tensorflow")`.

I am going to be out of the office for the next few hours but will come back to this later on today. Let me know what you find out via experimentation in the meantime.

**Comment by jjallaire** [comment]
It looks like on Ubuntu Desktop if you define the environment variables in `~/.profile` rather than `~/.bashrc` then they will be seen by both bash and  desktop applications. See https://help.ubuntu.com/community/EnvironmentVariables#A.2BAH4-.2F.profile

Note however that this file won't be read by bash if ~/.bash_profile or ~/.bash_login exists. This file will in turn source ~/.bashrc so you can put any environment variables / bash that you *only* want available in bash in that file. 

Note that also that you need to restart your display manager in order for these environment variables to be visible.

**Comment by jjallaire** [comment]
I've added to the instructions for GPU installation based on our discussion here:

https://tensorflow.rstudio.com/installation.html#cpu_vs_gpu

Let me know if that all works for you and if you'd suggest any changes to the documentation.

**Comment by madcarrot** [comment]
Thank you so much for the quick turn-around! 

I tried all three workarounds (but not sure if I implemented all of them correctly):
1. directly running from `bash` works
2. Adding CUDA path to `LD_LIBRARY_PATH` in the `Exec` line for `rstudio.desktop` works
3. Adding `LD_LIBRARY_PATH=...` to `/etc/environment` doesn't seem to work... 

Let me try `install_tensorflow(gpu = TRUE)` on your updated documentation page :)

**Comment by madcarrot** [comment]
Uhm, I tried `install_tensorflow(gpu = TRUE)` and it ran into 404 error. I think its the package location coded in the install command that doesn't match with the current `url`?
The `url` used in `install_tensorflow(gpu = TRUE)` is:
```https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-1.1.0-cp36-cp36m-linux_x86_64.whl```
While the one on Tensorflow's install page is:
```https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.1.0-cp36-cp36m-linux_x86_64.whl```

**Comment by jjallaire** [comment]
Drat! We did indeed have the wrong URL for the GPU version within conda. Just fixed, could you try again after installing from master?

**Comment by jjallaire** [comment]
As far as `/etc/environment` goes, a couple of things to consider/try:

1) You would need to restart your system for these variables to become available to new processes.

2) `/etc/environment` isn't a script file so variable expansion (e.g. LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64") wouldn't work there. See https://help.ubuntu.com/community/EnvironmentVariables#System-wide_environment_variables

3) Does it work if you edit ~/.profile rather than /etc/environment (remember that you need to restart for changes to ~/.profile to take effect.

**Comment by jjallaire** [comment]
FWIW on my Ubuntu 16.04 system changes to /etc/environment did indeed work once I restarted Ubuntu.

**Comment by jjallaire** [comment]
BTW this thread has motivated me to get GPU versions of TensorFlow installed on Linux and Windows. On Windows with a GTX 1080 Ti GPU I get a ~ 14x speedup using the GPU version of TensorFlow!!! 

My only regret is that NVIDIA doesn't make it a bit easier to get all the software installed and working correctly. Hopefully that will improve over time.

**Comment by madcarrot** [comment]
Haha no worries, yea now `install_tensorflow(gpu=T)` installs the GPU version correctly. Nice fix!

I didn't try changing `/etc/environment`, but changing `~/.profile` and then restarting the computer works for me. I assume `/etc/environment` will work the same way.

That's awesome! I'm so much more used to R, and being able to call Tensorflow from R with the full performance is definitely making me happier ;)

Indeed, it was an ordeal to get GPU version to work even on Ubuntu... lol

**Comment by jjallaire** [comment]
I've now created a standalone article on installing the GPU version that collects everything I've learned to date about what to do, gotches, etc.:

https://tensorflow.rstudio.com/installation_gpu.html

Let me know if you think anything requires further clarification or if there is anything else you'd add.

**Comment by madcarrot** [comment]
That's awesome! I've went through the ordeal of getting GPU Tensorflow working before this so my opinion is probably not objective, but I think the article contains all the essential information needed when I set it up earlier.

**Comment by jjallaire** [comment]
Great, thanks!

**Comment by madcarrot** [comment]
Thank you so much for helping! :D

**Comment by harvineet** [comment]
One thing I struggled with is installing the correct version of Tensorflow, which is compatible with the CUDA version on the machine.
For example, for me the following commands
`library(tensorflow)`
`install_tensorflow(version = "gpu")`
installed the latest version of Tensorflow which works with CUDA 9.0, whereas I had CUDA 8.0. 

For CUDA 8.0, this worked (in addition to following the steps in the documentation [here](https://tensorflow.rstudio.com/tensorflow/articles/installation_gpu.html))
`library(tensorflow)`
`install_tensorflow(version = "1.4.1-gpu")`

@jjallaire Might be helpful to mention this in the documentation, as it has instructions to install CUDA Toolkit v8.0 specifically.

Related discussion on [tensorflow project](https://github.com/tensorflow/tensorflow/issues/16670).
Related [Stack Overflow question](https://stackoverflow.com/questions/48575900/how-to-install-tensorflow-gpu-with-cuda8-0).

**Comment by eddelbuettel** [comment]
Really excellent point. I too have CUDA 8.0 "easily" on the current Ubuntu, and CUDA 9.0 would be a manual headache.  I had not realized I could 'fill in' with a matching tensorflow version, but that worked as advertised.  Thanks for the tip!
