### ISSUE TITLE
Can't find Python 27

### ISSUE THREAD

**Issue by StevenLShafer** [rstudio/tensorflow#129]
I have python 2.7 and 3.5 installed. Current tensorflow instructions recommend 3.5. However, I cannot get beyond the following error in Rstudio:

tf$Session()
Error in system2(python, stdout = TRUE, args = c("-c", shQuote("import sys; import platform; sys.stdout.write(platform.architecture()[0])"))) :
'"C:\Python27/python.exe"' not found

My attempts to set TENSORFLOW_PYTHON as recommended in the document don't help. Is Python27 hardcoded somewhere?

I see elsewhere that this issue might have been raised and resolved, but the recommendations in the installation document to override python27 don't seem to work.

(This was originally posted elsewhere, but Fritz Obermeyer suggested that I make it a new issue. I have a pseudo-fix to follow.)

**Comment by StevenLShafer** [comment]
I fixed this in typical debugging fashion:
1. I uninstalled tensorflow
2. I uninstalled Python 3.5
3. Rebooted (a couple of times, of course)
4. Reinstalled Python 3.5 "for all users". That places Python in "c:/Program Files" rather than in my own Appdata. Perhaps that is where rStudio was looking for it.
5. Reinstalled tensorflow-gpu.

That managed to fix the problem. However, it is very unsatisfying, because it doesn't provide any insight into what the problem was in the first place. 

I also need to mention that tensorflow-gpu is very difficult to get running for an incredibly annoying reason: the file "udnn64_X.dll" must EXACTLY match the file used when tensorflow is compiled by Google. It turns out that the current release of tensorflow was compiled using udnn64_5.dll. However, the current distribution from nVidia is udnn64_6.dll. Tensorflow can't find it, so it just says "failed to launch". I found a website that recommended changing the name of the dll, but that fails because you get a message (finally.....) that the wrong dll is running. This might have contributed to the tensorflow problems I had in R, which showed up by not finding the Python compiler. I mention it here mostly because there needs to be a clear place somewhere on the web for this information. It isn't on Google's site - they just say to be sure that udnn.dll is in the path. That's of no help if it is the wrong version of the dll.

**Comment by jjallaire** [comment]
Thank you for the bug reports and commentary!!!

The first issue is because for whatever reason there is no python.exe in C:\Python27 (or that there is no C:\Python27 in spite of the fact that there is a registry entry which indicates there should be). There could be many reasons for this and we should be more resilient against these "missing" components (we should just skip them rather than yielding an error). I'll fix that soon.

In terms of the GPU installation, I agree it is atrociously difficult! I think we might need some code in the tensorflow package to detect these subtle problems and suggest resolutions.
