### ISSUE TITLE
Fail in py_config() call

### ISSUE THREAD

**Issue by pingfreud** [rstudio/tensorflow#17]
Nice working making tf available from R interface :D

I'm having a small problem when trying to install:
`devtools::install_github("rstudio/tensorflow")`
I get:

```
Error : .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_config()
  error: Unable to parse -L from -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
Error: loading failed
Execution halted
```

I believe it has to do with g++ compiling the package in:
```
g++ -std=c++11 -shared -L/home/pingfreud/anaconda3/lib/R/lib -L/home/pingfreud/anaconda3/lib -lgfortran -o tensorflow.so RcppExports.o python.o -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -L/home/pingfreud/anaconda3/lib/R/lib -lR
```

I installed tf using:
```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl
sudo pip install --upgrade $TF_BINARY_URL
```
Tf is working normally when called from python2.7.

I tried setting TENSORFLOW_PYTHON  directly to /usr/bin/python2.7 and also setting TENSORFLOW_PYTHON_VERSION to 2.7 but I still get the same error message.

**Comment by jjallaire** [comment]
The configure script should have failed sooner with a more clear error (I've just updated it so it will in the future). Net is that we can't use anaconda python because it's not built in a way that it's easy to dynamically link against (AFAICT anaconda wants compiled code that links to it to itself be a conda package, which doesn't work very well for R users unless they want to turn all R package installation and management over to conda).

**Comment by eddelbuettel** [comment]
I am still trying to figure out what we all did wrong so that we all got this CentOS penance.

**Comment by jjallaire** [comment]
I just made a change to not require -L here: https://github.com/rstudio/tensorflow/commit/6586cc5457e7b72b2c528356b64380326d634e9d

Here's the downstream implication: in order for dynamically attaching to numpy to work on Linux we need to pre-load the libpython2.7.so so that the symbols are globally available. We do this here: https://github.com/rstudio/tensorflow/blob/master/src/python.cpp#L768-L781

Now the call to `dlopen` will not have a full path but rather just `libpython2.7.so`. If that works then we are home free, if not we need to figure out some other method to get our mitts on the full path to libpython.

**Comment by bwlewis** [comment]
Perhaps use:
```
python2.7-config --prefix

/usr/local
```

Not sure if this is fragile. In the from source installation of Python on CentOS, the libraries end up in /usr/local/lib  (note, *not* /usr/local/lib64). I know we all love RedHat, but for some terrible reason it's in wide use out there :(

**Comment by jjallaire** [comment]
Is there any way to tease out the "lib" part from python-config or would I
just have to hard code "lib" as the suffix?

**Comment by eddelbuettel** [comment]
It always used to be `/usr/local/lib` and `/usr/lib` before the multi-arch aspect crept in and added `64`.

**Comment by bwlewis** [comment]
If you call python-config --prefix and assign it to a variable in the compilation configuration (similar to PKG_LIBS), then something like this might work:

```{r}
libpath = Map(function(x) any(grepl("^libpython", dir(x))) , file.path(PYTHON_PREFIX, list("lib", "lib64",)))
names(libpath)[which(Reduce(c, libpath))]
```
ugly tho.

**Comment by jjallaire** [comment]
Okay, I just added code to use `--prefix` as a fallback. Does this work in your setup?

**Comment by bwlewis** [comment]
It's OK. It actually worked already after https://github.com/rstudio/tensorflow/commit/6586cc5457e7b72b2c528356b64380326d634e9d

CentOS can be a real pain for tensorflow. Maybe docker or some other virtual environment is a better approach for those users, esp. on CentOS 6.

**Comment by jjallaire** [comment]
Okay, then I'm going to revert this:
https://github.com/rstudio/tensorflow/commit/1394751e33cd30a74cf25944e47bf1ccbed3efc1

The idea being is that if python-config isn't adding a -L it thinks the
library can be found on the standard OS search path. I can bring back the
"--prefix" code later if need be.
