### ISSUE TITLE
RunMetadata/RunOptions crashes with tensorflow-gpu

### ISSUE THREAD

**Issue by synikitin** [rstudio/tensorflow#178]
Hello,

My setup is 

- Centos 7.0 (3.10.0-514.2.2.el7.x86_64)
- cuda 8.0
- cudnn 6.0
- Python 2.7
- Tensorflow 1.3 for gpu
- R 3.3.2
- Tensorflow R package 1.3.1

I have time and memory benchmarks run once in a while during a training loop with a code similar to this:

```
library(tensorflow)

with(
  tf$device('/gpu:0'), {
  x = tf$placeholder(tf$float32, shape(2L, 2L))
  y = tf$reduce_sum(x, 1L)
})

sess = tf$Session(config = tf$ConfigProto(log_device_placement = TRUE))
sess$run(tf$global_variables_initializer())

run_options = tf$RunOptions(trace_level = tf$RunOptions$FULL_TRACE)
run_metadata = tf$RunMetadata()
out = sess$run(
  y,
  feed_dict = dict(x = matrix(1:4, 2, 2)),
  options = run_options,
  run_metadata = run_metadata
)
```

If I start R inside a terminal, then it works fine; during the execution, I get a confirmation message about using a cuda profiling library, like this: 

> 2017-09-19 16:14:54.038639: I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libcupti.so.8.0 locally

However, if I run the program from inside Rstudio, it causes a crash. Rstudio also crashes if I assign all operations to a cpu device. However, it does work on cpu-only tensorflow. Any ideas? 

Thanks.

**Comment by jjallaire** [comment]
This is likely due to the (lack of) CUDA environment variables inside the RStudio session. There are a couple of ways around this:

1) Ensure that your desktop applications in CentOS also have access to the CUDA environment variables / PATH entries that your shell has access to. This is discussed in detail here: 

    - For desktop installations: https://tensorflow.rstudio.com/tensorflow/articles/installation_gpu.html#single-user-installation
    - For server installations: https://tensorflow.rstudio.com/tensorflow/articles/installation_gpu.html#multi-user-installation

2) If you are in a desktop configuration you can launch RStudio from within a bash terminal where the environment variables are defined and it will inherit them, e.g.

```bash
$ rstudio
```

**Comment by synikitin** [comment]
Yeah, fixing ld_config_path system-wide did it. Thanks!

**Comment by jjallaire** [comment]
Great, glad that fixed it!
