### ISSUE TITLE
Error when installing TensorFlow

### ISSUE THREAD

**Issue by yudizhangzyd** [rstudio/tensorflow#241]
> install_tensorflow()
Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Installing TensorFlow...
Collecting tensorflow==1.7.1 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl
  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl
  Could not install requirement tensorflow==1.7.1 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl
Could not install requirement tensorflow==1.7.1 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl for URL https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl
Error: Error 1 occurred installing packages into conda environment r-tensorflow

**Comment by goldingn** [comment]
I think the issue here is that the apparent latest version, scraped by `tensorflow:::install_tensorflow_conda()` [here](), doesn't correspond to a valid wheel URL, hence the 404 error. I'm not sure of the logic behind that scraping code, but it also appears to fail if you don't have the 3rd part of the version number there. Ie. this fails:
`install_tensorflow("conda", version = "1.8")`

@yudizhangzyd, try this for a quick fix: `install_tensorflow(version = "1.8.0")`

**Comment by jjallaire** [comment]
I've made a change to workaround this in the dev version of the TF package which can be installed with:

```r
devtools::install_github("rstudio/tensorflow")
```

**Comment by yudizhangzyd** [comment]
It worked now! Thank you so much!
