### ISSUE TITLE
benchmark of speed against python api

### ISSUE THREAD

**Issue by smilesun** [rstudio/tensorflow#251]
Is there any benchmark study to evaluate the speed behavior compared to the python api?

**Comment by jjallaire** [comment]
It should be approximately the same (since the R API is a very thin layer over the Python API). When using Keras, we re-order the input data to be row rather than column-based (as that yields better training performance). The overhead of this copy might or might not be significant depending on how CPU intensive your training is (as training gets more expensive the copy basically just washes out).

**Comment by smilesun** [comment]
what happens if I use the R API to do reinforcement learning? In which case there is only a small batch training with epoch 1 or more, and the overhead of transition from R to python accumulates over time? 
Is there a better solution for this case?

**Comment by jjallaire** [comment]
The overhead for a call to Python should be on the order of 1 or 2ms. Are you making tens of thousands of calls?

**Comment by smilesun** [comment]
usually in reinforcement learning, one make not only tens of thousands of calls but in millions.  So is there any way to avoid the overhead?

**Comment by eddelbuettel** [comment]
@smilesun What @jjallaire is trying to say that you may have _one_ call from R down to Python and C++ where your _bazillions calls with RL_ are all independent of how you called it.  Reticulate offers a very thin shim on top of the existing frameworks.  In general, these do _not_ call back to R so you may be concerned about a a non-problem.

**Comment by eddelbuettel** [comment]
Yep.  So you want (repeated) function calls as far down the stack as you can -- just like loops.

**Comment by jjallaire** [comment]
You might want to post same sample code here. One thing I am suspicious of is the need to make millions of calls in the first place, as the design of TF is create an execution graph that runs entirely within the TF C++ runtime (not even Python code executes in the graph). Python is generally simply an authoring tool for these graphs and R is the same (thus the performance difference is negligible since TF programs typically don't execute much if any Python code either, it's just used for authoring).

Again, I might be missing something by not fully understanding your use case. Sample code would help us give you a better answer.

**Comment by smilesun** [comment]
I implemented a reinforcement learing package and this algorithm is slow, have not figured out why, all the rest is fast. 
https://github.com/smilesun/rlR/blob/master/R/agent_pg_ddpg.R


the example to run is 
```
  library(rlR)
  env = makeGymEnv("Pendulum-v0")
  agent = makeAgent("AgentDDPG", env, getDefaultConf("AgentDQN"))
  agent$learn(1)

```

**Comment by smilesun** [comment]
the paper is Lillicrap, T. P., Hunt, J. J., Pritzel, A., Heess, N., Erez, T., Tassa, Y., … Wierstra, D. (2016). Continuous control with deep reinforcement learning. In ICLR. https://doi.org/10.1561/2200000006

**Comment by smilesun** [comment]
so the question is everytime one call sess.run, there is no overhead anymore?
