### ISSUE TITLE
Is tensorflow connecting to a gpu

### ISSUE THREAD

**Issue by gmrwvu** [rstudio/tensorflow#487]
I am using Windows 10 on an HP ENVY desktop with a GeForce RTX 2060 card. I used the studio version of the driver rather than the gamer version. I installed tensorflow and keras and then used them in R as follows:
library(tensorflow)
install_tensorflow(version = "gpu")
library(keras)
install_keras(tensorflow = "gpu")

No problems. When I run keras programs such as those found at https://tensorflow.rstudio.com/tutorials/ they all work fine as well after a few minor adjustments for versions. 

To be sure tensorflow is connecting to the gpu, I ran the following test in R: 
tf$test$is_gpu_available() 
which came up false.

I went to the conda env r-reticulate to further validate that the GPU is not used, I activated the r-reticulate environment and ran python (it is version 3.7.11 of python)
import tensorflow as tf
tf.test.is_gpu_available() 

That came back false as well.

I then created a conda env called py37 as follows:
conda create --name py37 python==3.7.11
conda activate py37
conda install tensorflow
conda install keras
conda install tensorflow-gpu
conda install tensorflow-estimator
conda install keras-gpu

Again, the following was used to test the implementation:
import tensorflow as tf
tf.test.is_gpu_available() 

That now came back true.  
I then substituted py37 in place of r-reticulate in two places:
users/myuser/anaconda3/envs and users/myuser/appdata/local/r-miniconda/envs
and went back to R to run this test again
tf$test$is_gpu_available() 
which came up true now as well. 

The keras programs still work fine after this substitution. The directions I followed to install the tensorflow and keras libraries are at https://tensorflow.rstudio.com/installation/gpu/local_gpu/   
I feel I missed something in the installation but everything seemed to go fine until I tested for available gpus.

**Comment by t-kalinowski** [comment]
I'm pretty sure this is due to a mistmatch between the CUDA version you have installed and the CUDA version that tensorflow needs. Running `conda install tensorflow-gpu` is actually not recommended anymore, because the conda build typically lags the official TensorFlow release version by a lot. Tensorflow is installed via pip into the conda env `pip install tensorflow`, which by default gives you a GPU capable tensorflow installation, so long as you have the correct cuda version available.
Please take a look here for more detailed instructions and links for how to install cuda: 
https://www.tensorflow.org/install/gpu
At the current release, tensorflow needs CUDA 11.2 and cuDNN 8.1.0
