### ISSUE TITLE
Passing lists of tensors as arguments

### ISSUE THREAD

**Issue by hunzikp** [rstudio/tensorflow#49]
Hi all

Some tf functions expect a Python list of Tensors as an argument, e.g. tf.concat() and tf.pack(). Is there any elegant way to pass an R list of tensors to these functions? Simply using `tf$concat(concat_dim = 1, values = list(t1, t2), name = "concat1")` throws an error - I believe because the Tensors are passed as a tuple instead of a list.

I'm currently using the following (admittedly ugly) workaround:
```R
tf_concatenate <- function(tf, concat_dim, t1, t2, name) {
  tensorflow:::py_run_string("def tfcc(tf, concat_dim, t1, t2, name):
    return tf.concat(concat_dim, [t1, t2], name)")
  mn <- tensorflow::import("__main__")
  mn$tfcc(tf, as.integer(concat_dim), t1, t2, name)
}
```

**Comment by jjallaire** [comment]
It may be that we've got the default marshaling wrong for this case. Tuples might be sufficiently specialized that we should always marshal as a plain list unless e.g. a `tuple` wrapper function is called. @terrytangyuan Do you forsee any incompatibilities or other problems if we start converting all R lists to python lists? (currently we only make it a python list if it's a heterogeneous list of R types e.g. integer vector, character vector, etc.)

**Comment by terrytangyuan** [comment]
There might be issues but I don't have examples on top of my head yet. But it makes sense to me to only convert homogeneous list of R types. 

I'd suggest to play around with and reproduce more examples to see if we encounter any edge cases and if those edge cases are common. I wasn't expecting people to do a lot with low level APIs.

**Comment by jjallaire** [comment]
I've changed the handling of unnamed R lists to pass a Python list rather than a tuple. In reviewing the documentation for the tensorflow API it looks as if tuples are *mostly* used for return values and in the cases where tuples are used as inputs they almost always specify "list/tuple" (which likely just means that they call the python `tuple` function on the input before using it). 

We can add a special `tuple` function on the R side if we find evidence that there are circumstances where callers need to force lists to tuples.

@hunzikp Could you try again with the latest master to ensure that everything works as expected then close the issue?

**Comment by hunzikp** [comment]
Works like a charm, many thanks.
