### ISSUE TITLE
mamba support for install_tensorflow()

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/tensorflow#502]
A conda-based install of tensorflow, at on linux, can take 10's of minutes. I would be great if mamba was supported. It's not clear if one can specific mamba when calling `install_tensorflow()`, since there is currently no documentation on using conda

**Comment by t-kalinowski** [comment]
Hi, thanks for filing. 

I think that even in conda python environments, `install_tensorflow()` should use pip to do the actual installation. If it's invoking something like `conda install tensorflow` then it's likely a bug. mamba/conda dependency resolver shouldn't be invoked unless we're also changing the Python version at the same time. The current CRAN release of this package does attempt to specify the Python version, but current dev version of this package does not. 

Can you please try with the dev version of this package, and if that doesn't work, provide a little more info about your environment?

**Comment by t-kalinowski** [comment]
Do you know that the tensorflow wheels installed by `pip` are also GPU enabled?

In the jupyter notebook, what's likely happening is that reticulate is attempting to update the python version in the installation, and mamba's dependancy resolver is either failing or taking an inordinate amount of time to do so. This issue should be fixed in the dev version of this package, or in the interim, you can pass `install_tensorflow(conda_python_version = NULL)`

**Comment by nick-youngblut** [comment]
`install_tensorflow(conda_python_version = NULL)` seems to work. Thanks!
