### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by JamesHall3525** [rstudio/tensorflow#556]
Team,

I am following this how to guide and running into an error. 
### This is how I installed
install.packages("tensorflow")
library(reticulate)
path_to_python <- install_python()
virtualenv_create("r-reticulate", python = path_to_python)
library(tensorflow)
install_tensorflow(envname = "r-reticulate")
install.packages("keras")
library(keras)
install_keras(envname = "r-reticulate")

## Final Lines that causes the error
library(tensorflow)
library(keras)
c(c(x_train, y_train), c(x_test, y_test)) %<-% keras::dataset_mnist()

### RESULT:

Error: Valid installation of TensorFlow not found.  Python environments searched for 'tensorflow' package:  C:\Users\jhall\AppData\Local\r-miniconda\envs\r-reticulate\python.exe  Python exception encountered:  Traceback (most recent call last):   File "C:\Users\jhall\AppData\Local\R\win-library\4.2\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook     return _run_hook(name, _hook)   File "C:\Users\jhall\AppData\Local\R\win-library\4.2\reticulate\python\rpytools\loader.py", line 93, in _run_hook     module = hook()   File "C:\Users\jhall\AppData\Local\R\win-library\4.2\reticulate\python\rpytools\loader.py", line 117, in _hook     return _find_and_load(name, import_) ModuleNotFoundError: No module named 'tensorflow'   You can install TensorFlow using the install_tensorflow() function.

**Comment by JamesHall3525** [comment]
**UPDATE**
Screenshots Attached After running recommended code:

[screenshot.pptx](https://github.com/rstudio/keras/files/10707737/screenshot.pptx)

**Comment by t-kalinowski** [comment]
It looks like you have two environments named "r-reticulate", one a conda environment, the other a virtual environment. When you call `install_tensorflow()`, tensorflow (the python package) is installed into the virtual environment, but then reticulate is binding to the condaenv instead of the virtualenv. 

You can uninstall the miniconda env like this:
```reticulate::miniconda_uninstall()```
After this, reticulate should default to the virtual env where tensorflow is already installed.
