### ISSUE TITLE
tf$concat behave differently compared to Python TF

### ISSUE THREAD

**Issue by Miller-Zijie-Zhu** [rstudio/tensorflow#62]
I have two pieces of code. The first one in Python with tf:

    a = tf.Variable(np.array([[0.33, 0.33, 0.33]]), dtype = tf.float32)
    b = tf.Variable(np.array([[0.11, 0.22, 0.33], [0.44, 0.55, 0.66]]), dtype = tf.float32)
    tf.concat(0, [a, b])
This works fine. Now the second one in Rstudio tensorflow package:

    a = tf$Variable(matrix(c(0.33,0.33,0.33), nrow = 1), dtype = tf$float32)
    b = tf$Variable(matrix(c(0.11, 0.22, 0.33, 0.44, 0.55, 0.66), nrow = 2), dtype = tf$float32)
    tf$concat(0, list(a,b))
This results in the error: `Error in py_call(attrib, args, keywords) : basic_string::resize`
Could you help figure out why this happens? Also, could the error message be more specific, instead of being all the same? Thanks in advance!

**Comment by jjallaire** [comment]
The latest version of tensorflow from GitHub should yield a better error message. This is what I see on my setup:

```
Error in py_call(attrib, args, keywords) : 
  TypeError: Expected int32, got 0.0 of type 'float' instead.
Detailed traceback: 
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py (line414): _concat
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py (line710): apply_op
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py (line628): convert_to_tensor
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py (line180): _constant_tensor_conversion_function
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py (line163): constant
    /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packag
```

The issue is that the `0` is being passed a float (since R's default numeric type is float) whereas it needs to be explicitly passed as an integer like this:

```r
tf$concat(0L, list(a,b))
```

Docs on this are here: https://rstudio.github.io/tensorflow/using_tensorflow_api.html#numeric_types.

**Comment by Miller-Zijie-Zhu** [comment]
Thanks for helping! This solve the problem. However, after I deleted the tensorflow package and reinstalled it using `devtools::install_github("rstudio/tensorflow")`, the error message is still `basic_string::resize`. Could you help me with this? (The package version here shows 0.3.0).

**Comment by jjallaire** [comment]
I'm not sure, perhaps it's a platform or tensorflow/python version thing. Here is my platform info:

R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Mavericks 10.9.5

Here is my TF/Python info:

```
$python
[1] "/usr/local/bin/python"

$libpython
[1] "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib"

$numpy
[1] "/Library/Python/2.7/site-packages/numpy-1.11.1-py2.7-macosx-10.9-intel.egg/numpy/core/include"

Python 2.7.12
```

You can get this info for your system by executing the following code:

```r
tensorflow:::py_config()
system(paste(tensorflow:::py_config()$python, "--version"))
```

@terrytangyuan Let me know if there are any qualifications on where/when your new improved error printing code will work.

**Comment by Miller-Zijie-Zhu** [comment]
This is my platform info:

    CentOS Linux 7
    x86_64 GNU/Linux
    R version 3.3.2
    $python
    [1] "/bin/python"
    $libpython
    [1] "libpython2.7.so"
    $numpy (1.11.3)
    [1] "/usr/lib64/python2.7/site-packages/numpy/core/include"
Thanks!

**Comment by terrytangyuan** [comment]
I don't see any problem with the code itself. @Miller-Zijie-Zhu Could you check whether you have completely deleted the old package? Sometimes while the package is loaded and you've installed another version, RStudio would still display two packages installed with the same version number since 0.3.0 hasn't changed even after improved trackbacks. Also try use Rscript from console.

**Comment by Miller-Zijie-Zhu** [comment]
I have checked that I completely deleted the old package, and I checked the version of the loaded tensorflow is 0.3.0 by using `sessionInfo().` I also tried installing the package using Rscript from console. But it's still the same error message...

**Comment by pourzanj** [comment]
@Miller-Zijie-Zhu I'm having this same problem i.e. all I get is the following:

`Error in py_call(attrib, args, keywords) : basic_string::resize`

The Rcpp function `stop()` is called, so an exception must be thrown but instead of printing the `ostr` it's given, it prints `basic_string::resize`. Maybe along the way of throwing our `ostr` exception another `basic_string::resize` was thrown and that one was caught before the `ostr` exception? 

 Without looking in to the internals of Rcpp, the only thing I can guess is that it's an issue with different compilers? I'm using g++ what compiler are you using?  @terrytangyuan and @jjallaire what compilers are you using?

**Comment by eddelbuettel** [comment]
There actually _is_ a known Rcpp issue regarding `stop()`  which crept into 0.12.8.  Try the master which should become 0.12.9 over the next week or two.

**Comment by pourzanj** [comment]
Ah that's useful to know. Thanks @eddelbuettel . I am indeed using Rcpp 0.12.8. Now to figure out how to switch to 0.12.9

**Comment by pourzanj** [comment]
Ok that fixed the problem. Thank you again @eddelbuettel . @Miller-Zijie-Zhu I just installed the github version of Rcpp using the following command and that fixed things

`devtools::install_github("RcppCore/Rcpp")`

**Comment by Miller-Zijie-Zhu** [comment]
@pourzanj Unfortunately re-installing Rcpp does not solve the issue for me. The error message is still the same. The compiler I'm using is g++. Also, I'm curious about how you find out Rcpp's `stop()` is called and noticed the `*ostr` is not pointed? Probably I could find out something by doing that as well. Thank you!

**Comment by pourzanj** [comment]
What version of Rcpp do you have?

**Comment by Miller-Zijie-Zhu** [comment]
@pourzanj Sorry it's working! Previously there's some residual part of an older version of Rcpp left. Thanks a lot!
