### ISSUE TITLE
Passing NULL arguments to TensorFlow functions

### ISSUE THREAD

**Issue by dfalbel** [rstudio/tensorflow#63]
Running in R

```
x <- tf$placeholder(tf$float32, shape = shape(NULL, 784L))
tf$contrib$layers$fully_connected(x, 10L, activation_fn = NULL)
```
I get

`Tensor("fully_connected/Relu:0", shape=(?, 10), dtype=float32)`

In Python, running the equivalent:

```
>>> x = tf.placeholder(tf.float32, [None, 784])
>>> tf.contrib.layers.fully_connected(x, 10, activation_fn = None)
<tf.Tensor 'fully_connected/BiasAdd:0' shape=(?, 10) dtype=float32>
```

I would expect to get the same kind of Tensor (fully_connected/BiasAdd:0) in R. 
Maybe there's a problem on how R passes NULL arguments to Python here.

**Comment by jjallaire** [comment]
Good one, thanks for reporting!

Should be fixed here: https://github.com/rstudio/tensorflow/commit/926973dc830502897d5d2e5255888dcc5a65affa

It was indeed related to passing the `NULL`. The `NULL` was being dropped entirely rather than forwarded which resulted in the default parameter value of `nn.relu` being applied.

**Comment by dfalbel** [comment]
Thanks! I just tested and it works great now!
