### ISSUE TITLE
Implicit conversion length one list to scalar issue 

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tensorflow#83]
https://github.com/rstudio/tensorflow/blob/master/src/python.cpp#L762
https://github.com/rstudio/tensorflow/blob/master/src/python.cpp#L779

These implicit conversions are likely to cause issues. Especially when `dnn_hidden_units = c(10L)` and when it's passed into Python side, `enumerate()` won't work on scalars.

```
Type'int' object is not iterable

Detailed traceback: 
...
...
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 212, in _dnn_linear_combined_model_fn
    for layer_id, num_hidden_units in enumerate(dnn_hidden_units):
...
...
```

Are there reasons behind this implicit conversion? Could we remove it?

**Comment by jjallaire** [comment]
This actually goes to the heart of what's problematic about the  `tf$` style interface for end users. Many, many functions in the API require scalars rather than lists, however R has no scalar type so we use the convention of single-element vectors being scalars. We then document that to force something to be a list you need to use the `list` function:

https://rstudio.github.io/tensorflow/using_tensorflow_api.html#numeric-lists

Another thing we could do is use the `I` function to indicate "do not transform the type of this in any way" (RJson does this).

We could also make lists the norm and then have a special `scalar` function to force a scalar.

Unfortunately in all of these scenarios users need to be aware of this issue and code around it in the appropriate way whenever they encounter it. This is fine for package developers using the tensorflow package as a substrate for a higher level binding, but kind of rough on end users.

When creating a wrapper function, just use `as.list` to ensure that whatever object is passed is seen as a list rather than a scalar by Python.

**Comment by terrytangyuan** [comment]
Sounds good. I'll handle that in wrapper function then.
