### ISSUE TITLE
Passing arguments to tf$map_fn

### ISSUE THREAD

**Issue by axelurbiz** [rstudio/tensorflow#94]
This is a follow-up to #89. How can I pass additional arguments to tf$map_fn? For example, I'm trying to apply "tf$image$resize_image_with_crop_or_pad" to the "x_image" tensor using the code below with additional arguments. This is my attempt, but it fails:

```r
# Simulate image data
set.seed(1)
N_IMAGES = 100
images <- array(runif(32*32*3 * N_IMAGES) * 250, dim = c(N_IMAGES, 32, 32, 3))
images.lab <- sample(1L:10L, N_IMAGES, replace = TRUE)
labels <- matrix(0L, nrow = N_IMAGES, ncol = 10)
for (i in 1:N_IMAGES) {
  labels[i, ][images.lab[[i]]] <- 1
}
rm(images.lab)

library(tensorflow)
sess <- tf$InteractiveSession()

# Placeholders for images
x <- tf$placeholder(tf$float32, shape(NULL, 32L, 32L, 3L))
y_ <- tf$placeholder(tf$float32, shape(NULL, 10L))
x_image <- tf$reshape(x, shape(-1L, 32L, 32L, 3L))
distorted_image <- tf$map_fn(tf$image$resize_image_with_crop_or_pad, 
                             x_image, target_height = 24, 
                             target_width = 24)
Error in py_call(attrib, args, keywords) : 
  TypeError: map_fn() got an unexpected keyword argument 'target_width'
```
This is the function doc related to the TensorFlow version I'm using:
[https://www.tensorflow.org/versions/r0.12/api_docs/python/image/cropping](url)

Thanks,
Axel.

**Comment by jjallaire** [comment]
The problem is that `target_height` and `target_width` are actually being passed to `tf$map_fn` (since they are parameters of that function call) when what you really want is to use them as parameters to `tf$image$resize_image_with_crop_or_pad`.  

i.e. `tf$map_fn` takes only 2 arguments: the function to apply and the elements to apply it to. You can make your example work by defining an R function inline that calls `tf$image$resize_image_with_crop_or_pad` with the correct arguments:

```r
distorted_image <- tf$map_fn(function(image) {
  tf$image$resize_image_with_crop_or_pad(image, 
                                         target_height = 24L, 
                                         target_width = 24L)
}, elems = x_image)
```

**Comment by axelurbiz** [comment]
Thanks @jjallaire!
