### ISSUE TITLE
integration with the Tensorflow project?

### ISSUE THREAD

**Issue by woj-i** [rstudio/tensorflow#97]
Hi! Since Tensorflow 1.0 there is an experimental API for Java and Go, which IMO is a big step to have Tensorflow multilanguage. Unfortunatelt R is not present on the list of 4 (official) API languages...

What about including this API as a part of Tensorflow project? I am a beginner in Tensorflow environment, however I think integration would keep compatibility of interfaces and make R interface for TF more popular. 
Maybe it would be also possible to prepare R API for Keras, since a tight integration of TF and Keras have been anounced (https://twitter.com/fchollet/status/820746845068505088).
Please let me know on the roadmap of this project.

**Comment by eddelbuettel** [comment]
It is a little more complicated. TF is an official Google project, so Google gets to decide what they call official.

**Comment by jjallaire** [comment]
We could try to include the API within tensorflow proper, but I think we're better off having this package distributed on CRAN and compatible with all versions of tensorflow. Distributing on CRAN will of course allow other CRAN packages to build on top of it.

We absolutely intend to create native R APIs for both keras and TF.Learn, and in fact expect these to be the dominant ways that R users interact with tensorflow (although we think having access to the lower-level APIS is also critical, which is why we are working on that first).

The issue of promotion is a separate one, and I think once we've gotten the R APIs further along we'll work harder on this. We are also working closely with Google both on TF and CloudML. In fact we are co-presenting with them at Google Cloud NEXT in a couple of weeks: https://cloudnext.withgoogle.com/schedule#target=lifecycle-of-a-machine-learning-model-1fa252d7-6ceb-4419-adf9-6a041b814b28.
